name: Auto-Pixai

# 定义触发条件：push 到 main 分支、pull request 到 main 分支、以及每日定时任务
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 1 * * *'  # 每天 UTC 时间凌晨 1 点运行

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Dependencies
      run: npm install

    - name: Run Puppeteer Script
      env:
        LOGINNAME: ${{ secrets.LOGINNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
      run: |
        npm start
